export type FilterName =
  | 'DATE_FILTER'
  | 'CREATION_DATE_FILTER'
  | 'FINISH_DATE_FILTER'
  | 'DEADLINE_DATE_FILTER'
  | 'IS_OVERDUE_FILTER'
  | 'ASSIGNER_FILTER'
  | 'EXECUTOR_FILTER'
  | 'STATUS_FILTER'
  | 'PRIORITY_FILTER'
  | 'TAGS_FILTER'
  | 'MODE_FOCUS_FILTER'
  | 'FOLDER_FILTER'
  | 'SPRINT_FILTER'

//DATE_FILTER_DATA

//ASSIGNER_FILTER_DATA
export type UserFilterData = number[]
//MODE_FOCUS_FILTER_DATA
//FINISHED_TASK_FILTER_DATA
